//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeSharp.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TradeSharp.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No country/International.
        /// </summary>
        public static string CountryInternationalName {
            get {
                return ResourceManager.GetString("CountryInternationalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of data provider &quot;{0}&quot;.
        /// </summary>
        public static string DataProviderCreateFail {
            get {
                return ResourceManager.GetString("DataProviderCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one data provider needs to be defined..
        /// </summary>
        public static string DataProviderRequired {
            get {
                return ResourceManager.GetString("DataProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create instance of data store &quot;{0}&quot;.
        /// </summary>
        public static string DataStoreCreateFail {
            get {
                return ResourceManager.GetString("DataStoreCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ExchangeNoneName {
            get {
                return ResourceManager.GetString("ExchangeNoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank fundamental definition.
        /// </summary>
        public static string FundamentalNoneDescription {
            get {
                return ResourceManager.GetString("FundamentalNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FundamentalNoneName {
            get {
                return ResourceManager.GetString("FundamentalNoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable &quot;{0}&quot; not found, required for home directory configuration.
        /// </summary>
        public static string HomeDirectoryMissing {
            get {
                return ResourceManager.GetString("HomeDirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string InstrumentGroupRootDescription {
            get {
                return ResourceManager.GetString("InstrumentGroupRootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        public static string InstrumentGroupRootName {
            get {
                return ResourceManager.GetString("InstrumentGroupRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root instrument group can not be removed.
        /// </summary>
        public static string InstrumentGroupRootNoRemove {
            get {
                return ResourceManager.GetString("InstrumentGroupRootNoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instrument.
        /// </summary>
        public static string InstrumentNoneDescription {
            get {
                return ResourceManager.GetString("InstrumentNoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string InstrumentNoneName {
            get {
                return ResourceManager.GetString("InstrumentNoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No text available&gt;.
        /// </summary>
        public static string NoTextAvailable {
            get {
                return ResourceManager.GetString("NoTextAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required parameter &quot;{0}&quot; not found..
        /// </summary>
        public static string ParameterNotFound {
            get {
                return ResourceManager.GetString("ParameterNotFound", resourceCulture);
            }
        }
    }
}
